workflows:
  android-workflow:
    name: Email Test Workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      flutter: stable
      groups:
        - email-variables

    triggering:
      events:
        - push
      branch_patterns: # Include or exclude watched branches
        - pattern: "*"
          include: true
          source: true


    scripts:
      - name: Dynamic email change
        script: |
          export email_address="jakob.erben@js-soft.com"
          echo $email_address 

    publishing:
      email:
        recipients:
          - $email_address
        notify:
          success: true
          failure: true