workflows:
  android-workflow:
    name: Tagging Test Workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      flutter: stable
      groups:
        - release_parameters
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: "*"
          include: true
      cancel_previous_builds: false

    scripts:
      - name: Set up local.properties
        script: echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"

      - name: Get Flutter packages
        script: flutter pub get

      - name: Tag Formatting and Verification
        script: |
          echo "The tag which triggered the build is $CM_TAG"  
          echo "postfix is $tag_postfix"
          echo "prefix is $tag_prefix" 
          prefix_removed=$(cut -d $tag_prefix -f2 <<< $CM_TAG)
          cleaned=$(cut -d $tag_postfix -f1 <<< $prefix_removed)
          echo "The cleaned tag is $cleaned"
          major=$(cut -d '.' -f1 <<< $cleaned)
          minor=$(cut -d '.' -f2 <<< $cleaned)
          patch=$(cut -d '.' -f3 <<< $cleaned)
          regex='^[0-9]+$'
          if [[ ! $major =~ $regex ]] || [[ ! $minor =~ $regex ]] || [[ ! $patch =~ $regex ]]; then
            echo "Tag is not a valid version. [major].[minor].[patch] expected. (Major, minor and patch must be two digit numbers!). Got $major.$minor.$patch"
            exit 1
          fi
      #Insert some form of tag verification
      - name: Build Android-Application-Bundle  with Flutter
        script: |
          BUILD_NUMBER=1
          flutter build appbundle --release \
            --build-name=$CM_TAG \
            --build-number=$BUILD_NUMBER \

    artifacts:
      - build/**/outputs/flutter-apk/*.apk
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log # this does not have to be present when the command fails...

    publishing:
      scripts:
        - name: Display the file listings for all needed things
          script: echo "Listing all files in the build directory" && ls -la build
