workflows:
  android-workflow:
    name: Tagging Test Workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      flutter: stable
      groups:
        - email-variables
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: "*"
          include: true
      cancel_previous_builds: false

    scripts:
      - name: Set up local.properties
        script: echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"

      - name: Get Flutter packages
        script: flutter pub get

      - name: Build Android-Application-Bundle  with Flutter
        script: |
          BUILD_NUMBER=1
          flutter build appbundle --release \
            --build-name=$CM_TAG \
            --build-number=$BUILD_NUMBER \

    artifacts:
      - build/**/outputs/flutter-apk/*.apk
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log # this does not have to be present when the command fails...

    publishing:
      scripts:
        - name: Display the file listings for all needed things
          script: echo "Listing all files in the build directory" && ls -la build
