workflows:
  android-workflow:
    name: Tagging Test Workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      flutter: stable
      groups:
        - release_parameters
    triggering:
      events:
        - tag

    scripts:
      - name: Set up local.properties
        script: echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"

      - name: Get Flutter packages
        script: flutter pub get

      - name: Tag Formatting and Verification
        script: |
          echo "The tag which triggered the build is $CM_TAG"  
          cleaned=$(awk -F 'v' '{print $2}' <<< $CM_TAG)
          echo "The cleaned tag is $cleaned"

          major=$(cut -d '.' -f1 <<< $cleaned)
          minor=$(cut -d '.' -f2 <<< $cleaned)
          patch=$(cut -d '.' -f3 <<< $cleaned)
          if [[ ! $major =~ ^[0-9]+$ ]] || [[ ! $minor =~ ^[0-9]+$ ]] || [[ ! $patch =~ ^[0-9]+$ ]]; then
            echo "$major.$minor.$patch is not a valid version. Each part must match the regex set in the codemagic variables!)"
            exit 1
          fi

          echo $cleaned > tag_cleaned.txt

      #Insert some form of tag verification
      - name: Build Android-Application-Bundle  with Flutter
        script: |
          cleaned_tag=$(cat tag_cleaned.txt)
          echo "Building with the following tag: $cleaned_tag"
          BUILD_NUMBER=1
          flutter build appbundle --release \
            --build-name=$cleaned_tag \
            --build-number=$BUILD_NUMBER \

    artifacts:
      - build/**/outputs/**/*.aab
      - flutter_drive.log # this does not have to be present when the command fails...

    publishing:
      scripts:
        - name: Display the file listings for all needed things
          script: echo "Listing all files in the build directory" && ls -la build
